# Generated by Django 5.1.2 on 2024-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_headerthings_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="avatar",
            field=models.FileField(null=True, upload_to="logo_person"),
        ),
    ]
